services:
  db:
    image: postgres:15
    container_name: local-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data

  backend:
    container_name: local-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      bash -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  app-db-data:
