// This file is auto-generated by @hey-api/openapi-ts

export const AttemptSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        student_id: {
            type: 'string',
            format: 'uuid',
            title: 'Student Id'
        },
        test_id: {
            type: 'string',
            format: 'uuid',
            title: 'Test Id'
        },
        score: {
            type: 'integer',
            title: 'Score',
            default: 0
        },
        status: {
            '$ref': '#/components/schemas/AttemptStatus',
            default: 'ongoing'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        submitted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Submitted At'
        },
        tab_switch_count: {
            type: 'integer',
            title: 'Tab Switch Count',
            default: 0
        },
        ai_analysis: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Analysis'
        },
        section_results: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Section Results'
        }
    },
    type: 'object',
    required: ['student_id', 'test_id'],
    title: 'Attempt'
} as const;

export const AttemptAnswerPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        question_id: {
            type: 'string',
            format: 'uuid',
            title: 'Question Id'
        },
        selected_option: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Selected Option'
        },
        answer_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Answer Text'
        },
        is_correct: {
            type: 'boolean',
            title: 'Is Correct'
        },
        marks_obtained: {
            type: 'integer',
            title: 'Marks Obtained'
        },
        time_spent_seconds: {
            type: 'integer',
            title: 'Time Spent Seconds'
        },
        question_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Question Text'
        },
        solution_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Solution Text'
        },
        correct_option: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Correct Option'
        },
        correct_answer_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Correct Answer Text'
        }
    },
    type: 'object',
    required: ['id', 'question_id', 'is_correct', 'marks_obtained', 'time_spent_seconds'],
    title: 'AttemptAnswerPublic'
} as const;

export const AttemptPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        student_id: {
            type: 'string',
            format: 'uuid',
            title: 'Student Id'
        },
        test_id: {
            type: 'string',
            format: 'uuid',
            title: 'Test Id'
        },
        score: {
            type: 'integer',
            title: 'Score'
        },
        status: {
            '$ref': '#/components/schemas/AttemptStatus'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        submitted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Submitted At'
        },
        tab_switch_count: {
            type: 'integer',
            title: 'Tab Switch Count'
        },
        ai_analysis: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Analysis'
        },
        answers: {
            items: {
                '$ref': '#/components/schemas/AttemptAnswerPublic'
            },
            type: 'array',
            title: 'Answers',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'student_id', 'test_id', 'score', 'status', 'started_at', 'tab_switch_count'],
    title: 'AttemptPublic'
} as const;

export const AttemptStatusSchema = {
    type: 'string',
    enum: ['ongoing', 'submitted'],
    title: 'AttemptStatus'
} as const;

export const Body_ai_integration_upload_pdfSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_ai-integration-upload_pdf'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_omega_omega_uploadSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        },
        config: {
            type: 'string',
            title: 'Config'
        }
    },
    type: 'object',
    required: ['file', 'config'],
    title: 'Body_omega-omega_upload'
} as const;

export const Body_omr_process_omrSchema = {
    properties: {
        test_id: {
            type: 'string',
            format: 'uuid',
            title: 'Test Id'
        },
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['test_id', 'file'],
    title: 'Body_omr-process_omr'
} as const;

export const Body_tests_create_testSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        duration_minutes: {
            type: 'integer',
            title: 'Duration Minutes'
        },
        scheduled_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scheduled At'
        },
        standard: {
            type: 'string',
            title: 'Standard'
        },
        category: {
            type: 'string',
            title: 'Category'
        },
        positive_marks: {
            type: 'integer',
            title: 'Positive Marks',
            default: 4
        },
        negative_marks: {
            type: 'number',
            title: 'Negative Marks',
            default: -1
        },
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['title', 'duration_minutes', 'file'],
    title: 'Body_tests-create_test'
} as const;

export const CreateOrderRequestSchema = {
    properties: {
        grade: {
            type: 'integer',
            title: 'Grade'
        }
    },
    type: 'object',
    required: ['grade'],
    title: 'CreateOrderRequest'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const QuestionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        question_text: {
            type: 'string',
            title: 'Question Text'
        },
        option_a: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Option A'
        },
        option_b: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Option B'
        },
        option_c: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Option C'
        },
        option_d: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Option D'
        },
        options: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Options'
        },
        marks: {
            type: 'integer',
            title: 'Marks'
        },
        negative_marks: {
            type: 'number',
            title: 'Negative Marks'
        },
        subject: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subject'
        },
        section: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Section'
        },
        question_type: {
            type: 'string',
            title: 'Question Type',
            default: 'MCQ'
        },
        question_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Question Number'
        },
        solution_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Solution Text'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        }
    },
    type: 'object',
    required: ['id', 'question_text', 'marks', 'negative_marks'],
    title: 'QuestionPublic'
} as const;

export const SubmitQuestionResponseSchema = {
    properties: {
        question_id: {
            type: 'string',
            format: 'uuid',
            title: 'Question Id'
        },
        selected_option: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Selected Option'
        },
        answer_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Answer Text'
        },
        time_spent_seconds: {
            type: 'integer',
            title: 'Time Spent Seconds',
            default: 0
        }
    },
    type: 'object',
    required: ['question_id'],
    title: 'SubmitQuestionResponse'
} as const;

export const SubmitTestRequestSchema = {
    properties: {
        test_id: {
            type: 'string',
            format: 'uuid',
            title: 'Test Id'
        },
        responses: {
            items: {
                '$ref': '#/components/schemas/SubmitQuestionResponse'
            },
            type: 'array',
            title: 'Responses'
        },
        tab_switch_count: {
            type: 'integer',
            title: 'Tab Switch Count',
            default: 0
        }
    },
    type: 'object',
    required: ['test_id', 'responses'],
    title: 'SubmitTestRequest'
} as const;

export const SystemSettingPublicSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        value: {
            type: 'string',
            title: 'Value'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['key', 'value'],
    title: 'SystemSettingPublic'
} as const;

export const SystemSettingUpdateSchema = {
    properties: {
        value: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Value'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'SystemSettingUpdate'
} as const;

export const TestSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        instructions: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Instructions'
        },
        duration_minutes: {
            type: 'integer',
            title: 'Duration Minutes'
        },
        total_marks: {
            type: 'integer',
            title: 'Total Marks',
            default: 0
        },
        question_paper_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Question Paper Url'
        },
        standard: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Standard'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        created_by: {
            type: 'string',
            format: 'uuid',
            title: 'Created By'
        },
        subject_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subject Id'
        },
        is_published: {
            type: 'boolean',
            title: 'Is Published',
            default: false
        },
        scheduled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scheduled At'
        },
        positive_marks: {
            type: 'integer',
            title: 'Positive Marks',
            default: 4
        },
        negative_marks: {
            type: 'number',
            title: 'Negative Marks',
            default: -1
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'duration_minutes', 'created_by'],
    title: 'Test'
} as const;

export const TestPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        instructions: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Instructions'
        },
        duration_minutes: {
            type: 'integer',
            title: 'Duration Minutes'
        },
        total_marks: {
            type: 'integer',
            title: 'Total Marks'
        },
        question_paper_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Question Paper Url'
        },
        standard: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Standard'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        is_published: {
            type: 'boolean',
            title: 'Is Published'
        },
        scheduled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scheduled At'
        },
        positive_marks: {
            type: 'integer',
            title: 'Positive Marks'
        },
        negative_marks: {
            type: 'number',
            title: 'Negative Marks'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        questions: {
            items: {
                '$ref': '#/components/schemas/QuestionPublic'
            },
            type: 'array',
            title: 'Questions',
            default: []
        },
        submission_count: {
            type: 'integer',
            title: 'Submission Count',
            default: 0
        },
        average_score: {
            type: 'number',
            title: 'Average Score',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'title', 'duration_minutes', 'total_marks', 'is_published', 'positive_marks', 'negative_marks', 'created_at'],
    title: 'TestPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'student'
        },
        standard: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Standard'
        },
        stream: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stream'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        },
        is_premium: {
            type: 'boolean',
            title: 'Is Premium'
        },
        standard: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Standard'
        },
        stream: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stream'
        },
        grade: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade'
        },
        is_paid: {
            type: 'boolean',
            title: 'Is Paid'
        },
        payment_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Status'
        },
        payment_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Id'
        },
        fee_override: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fee Override'
        },
        is_fee_exempt: {
            type: 'boolean',
            title: 'Is Fee Exempt'
        },
        premium_expiry: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Premium Expiry'
        },
        last_active_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Active At'
        },
        current_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Path'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'email', 'full_name', 'role', 'is_superuser', 'is_premium', 'standard', 'stream', 'grade', 'is_paid', 'payment_status', 'payment_id', 'fee_override', 'is_fee_exempt', 'premium_expiry', 'last_active_at', 'current_path', 'created_at'],
    title: 'UserPublic'
} as const;

export const UserReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        role: {
            '$ref': '#/components/schemas/UserRole'
        }
    },
    type: 'object',
    required: ['id', 'email', 'role'],
    title: 'UserRead'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'student'
        },
        standard: {
            type: 'string',
            maxLength: 50,
            title: 'Standard'
        },
        stream: {
            type: 'string',
            maxLength: 50,
            title: 'Stream'
        }
    },
    type: 'object',
    required: ['email', 'password', 'standard', 'stream'],
    title: 'UserRegister'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['student', 'teacher', 'admin'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        role: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserRole'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VerifyPaymentRequestSchema = {
    properties: {
        razorpay_order_id: {
            type: 'string',
            title: 'Razorpay Order Id'
        },
        razorpay_payment_id: {
            type: 'string',
            title: 'Razorpay Payment Id'
        },
        razorpay_signature: {
            type: 'string',
            title: 'Razorpay Signature'
        }
    },
    type: 'object',
    required: ['razorpay_order_id', 'razorpay_payment_id', 'razorpay_signature'],
    title: 'VerifyPaymentRequest'
} as const;

export const app__schemas__user__UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        role: {
            '$ref': '#/components/schemas/UserRole'
        }
    },
    type: 'object',
    required: ['email', 'password', 'role'],
    title: 'UserCreate'
} as const;