// This file is auto-generated by @hey-api/openapi-ts

export type app__schemas__user__UserCreate = {
    email: string;
    password: string;
    role: UserRole;
};

export type Attempt = {
    id?: string;
    student_id: string;
    test_id: string;
    score?: number;
    status?: AttemptStatus;
    started_at?: string;
    submitted_at?: (string | null);
    tab_switch_count?: number;
    ai_analysis?: (string | null);
    section_results?: ({
        [key: string]: unknown;
    } | null);
};

export type AttemptAnswerPublic = {
    id: string;
    question_id: string;
    selected_option?: (string | null);
    answer_text?: (string | null);
    is_correct: boolean;
    marks_obtained: number;
    time_spent_seconds: number;
    question_text?: (string | null);
    solution_text?: (string | null);
    correct_option?: (string | null);
    correct_answer_text?: (string | null);
};

export type AttemptPublic = {
    id: string;
    student_id: string;
    test_id: string;
    score: number;
    status: AttemptStatus;
    started_at: string;
    submitted_at?: (string | null);
    tab_switch_count: number;
    ai_analysis?: (string | null);
    answers?: Array<AttemptAnswerPublic>;
};

export type AttemptStatus = 'ongoing' | 'submitted';

export type Body_ai_integration_upload_pdf = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_omega_omega_upload = {
    file: (Blob | File);
    config: string;
};

export type Body_omr_process_omr = {
    test_id: string;
    file: (Blob | File);
};

export type Body_tests_create_test = {
    title: string;
    description?: string;
    duration_minutes: number;
    scheduled_at?: (string | null);
    standard?: string;
    category?: string;
    positive_marks?: number;
    negative_marks?: number;
    file: (Blob | File);
};

export type CreateOrderRequest = {
    grade: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QuestionPublic = {
    id: string;
    question_text: string;
    option_a?: (string | null);
    option_b?: (string | null);
    option_c?: (string | null);
    option_d?: (string | null);
    options?: ({
        [key: string]: unknown;
    } | null);
    marks: number;
    negative_marks: number;
    subject?: (string | null);
    section?: (string | null);
    question_type?: string;
    has_visual?: boolean;
    visual_tag?: (string | null);
    question_number?: (number | null);
    page_number?: (number | null);
    visual_bbox?: ({
        [key: string]: unknown;
    } | null);
    solution_text?: (string | null);
    image_url?: (string | null);
};

export type SubmitQuestionResponse = {
    question_id: string;
    selected_option?: (string | null);
    answer_text?: (string | null);
    time_spent_seconds?: number;
};

export type SubmitTestRequest = {
    test_id: string;
    responses: Array<SubmitQuestionResponse>;
    tab_switch_count?: number;
};

export type SystemSettingPublic = {
    key: string;
    value: string;
    description?: (string | null);
};

export type SystemSettingUpdate = {
    value?: (string | null);
    description?: (string | null);
};

export type Test = {
    id?: string;
    title: string;
    description?: (string | null);
    instructions?: (string | null);
    duration_minutes: number;
    total_marks?: number;
    question_paper_url?: (string | null);
    standard?: (string | null);
    category?: (string | null);
    created_by: string;
    subject_id?: (string | null);
    is_published?: boolean;
    scheduled_at?: (string | null);
    positive_marks?: number;
    negative_marks?: number;
    created_at?: string;
};

export type TestPublic = {
    id: string;
    title: string;
    description?: (string | null);
    instructions?: (string | null);
    duration_minutes: number;
    total_marks: number;
    question_paper_url?: (string | null);
    standard?: (string | null);
    category?: (string | null);
    is_published: boolean;
    scheduled_at?: (string | null);
    positive_marks: number;
    negative_marks: number;
    created_at: string;
    questions?: Array<QuestionPublic>;
    submission_count?: number;
    average_score?: number;
    is_symmetrical?: (boolean | null);
    symmetry_message?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    password: string;
    full_name?: (string | null);
    is_superuser?: boolean;
    role?: UserRole;
    standard?: (string | null);
    stream?: (string | null);
};

export type UserPublic = {
    id: string;
    email: string;
    full_name: (string | null);
    role: UserRole;
    is_superuser: boolean;
    is_premium: boolean;
    standard: (string | null);
    stream: (string | null);
    grade: (number | null);
    is_paid: boolean;
    payment_status: (string | null);
    payment_id: (string | null);
    fee_override: (number | null);
    is_fee_exempt: boolean;
    premium_expiry: (string | null);
    last_active_at: (string | null);
    current_path: (string | null);
    created_at: string;
};

export type UserRead = {
    id: string;
    email: string;
    role: UserRole;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    role?: UserRole;
    standard: string;
    stream: string;
};

export type UserRole = 'student' | 'teacher' | 'admin';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    password?: (string | null);
    full_name?: (string | null);
    is_active?: (boolean | null);
    role?: (UserRole | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VerifyPaymentRequest = {
    razorpay_order_id: string;
    razorpay_payment_id: string;
    razorpay_signature: string;
};

export type AiIntegrationUploadPdfData = {
    formData: Body_ai_integration_upload_pdf;
};

export type AiIntegrationUploadPdfResponse = (unknown);

export type AttemptsSubmitTestData = {
    requestBody: SubmitTestRequest;
};

export type AttemptsSubmitTestResponse = (Attempt);

export type AttemptsReadUserAttemptsData = {
    limit?: number;
    skip?: number;
};

export type AttemptsReadUserAttemptsResponse = (Array<AttemptPublic>);

export type AttemptsGetAttemptStatsResponse = ({
    [key: string]: unknown;
});

export type AttemptsReadAttemptData = {
    id: string;
};

export type AttemptsReadAttemptResponse = (AttemptPublic);

export type AttemptsExportAttemptsData = {
    testId: string;
};

export type AttemptsExportAttemptsResponse = (unknown);

export type AuthRegisterData = {
    requestBody: app__schemas__user__UserCreate;
};

export type AuthRegisterResponse = (UserRead);

export type HealthCheckResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OmegaHealthCheckResponse = (unknown);

export type OmegaOmegaUploadData = {
    formData: Body_omega_omega_upload;
};

export type OmegaOmegaUploadResponse = (unknown);

export type OmrProcessOmrData = {
    formData: Body_omr_process_omr;
};

export type OmrProcessOmrResponse = (Attempt);

export type PaymentsCreateOrderData = {
    requestBody: CreateOrderRequest;
};

export type PaymentsCreateOrderResponse = (unknown);

export type PaymentsVerifyPaymentData = {
    requestBody: VerifyPaymentRequest;
};

export type PaymentsVerifyPaymentResponse = (unknown);

export type PaymentsPaymentWebhookData = {
    xRazorpaySignature?: string;
};

export type PaymentsPaymentWebhookResponse = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SettingsReadSettingsData = {
    limit?: number;
    skip?: number;
};

export type SettingsReadSettingsResponse = (Array<SystemSettingPublic>);

export type SettingsUpdateSettingData = {
    key: string;
    requestBody: SystemSettingUpdate;
};

export type SettingsUpdateSettingResponse = (SystemSettingPublic);

export type TestsCreateTestData = {
    formData: Body_tests_create_test;
};

export type TestsCreateTestResponse = (Test);

export type TestsReadTestsData = {
    limit?: number;
    skip?: number;
};

export type TestsReadTestsResponse = (Array<TestPublic>);

export type TestsReadTestData = {
    id: string;
};

export type TestsReadTestResponse = (TestPublic);

export type TestsDeleteTestData = {
    id: string;
};

export type TestsDeleteTestResponse = (unknown);

export type TestsGenerateQuestionsData = {
    id: string;
};

export type TestsGenerateQuestionsResponse = (Array<QuestionPublic>);

export type UsersExportExcelResponse = (unknown);

export type UsersExportCsvResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersUserHeartbeatData = {
    path: string;
};

export type UsersUserHeartbeatResponse = (UserPublic);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UsersUpdateUserFeeData = {
    feeOverride?: (number | null);
    isFeeExempt?: (boolean | null);
    userId: string;
};

export type UsersUpdateUserFeeResponse = (UserPublic);

export type UsersGetAdminStatsResponse = (unknown);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);