"""add_stream_and_standard_to_test

Revision ID: 06dac7ce5b4e
Revises: fe361ac9d9a8
Create Date: 2026-02-08 19:43:17.967060

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '06dac7ce5b4e'
down_revision = 'fe361ac9d9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('standard', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tests', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'category')
    op.drop_column('tests', 'standard')
    # ### end Alembic commands ###
