"""add payment and grade fields to user

Revision ID: 1347c9efcfae
Revises: 6c72d79e43ba
Create Date: 2026-02-13 01:59:56.612306

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1347c9efcfae'
down_revision = '6c72d79e43ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('grade', sa.Integer(), nullable=True)) # Already added in failed attempt
    op.add_column('user', sa.Column('is_paid', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('payment_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'payment_id')
    op.drop_column('user', 'payment_status')
    op.drop_column('user', 'is_paid')
    op.drop_column('user', 'grade')
    # ### end Alembic commands ###
