"""add marking scheme to test

Revision ID: 3d46a272b5b7
Revises: 06dac7ce5b4e
Create Date: 2026-02-08 21:54:38.002063

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
"""add marking scheme to test

Revision ID: 3d46a272b5b7
Revises: 06dac7ce5b4e
Create Date: 2026-02-08 21:54:38.002063

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3d46a272b5b7'
down_revision = '06dac7ce5b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('positive_marks', sa.Integer(), nullable=False, server_default='4'))
    op.add_column('tests', sa.Column('negative_marks', sa.Float(), nullable=False, server_default='-1.0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'negative_marks')
    op.drop_column('tests', 'positive_marks')
    # ### end Alembic commands ###
