"""add system_setting table

Revision ID: 3d8cc9d4266e
Revises: 1347c9efcfae
Create Date: 2026-02-13 13:58:05.860548

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3d8cc9d4266e'
down_revision = '1347c9efcfae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
