"""Add advanced user fields

Revision ID: 5aeac5d60a5c
Revises: f548096aeeb5
Create Date: 2026-02-16 09:33:24.339671

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5aeac5d60a5c'
down_revision = 'f548096aeeb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_columns = [c['name'] for c in inspector.get_columns('user')]

    if 'fee_override' not in existing_columns:
        op.add_column('user', sa.Column('fee_override', sa.Float(), nullable=True))
    if 'is_fee_exempt' not in existing_columns:
        op.add_column(
            'user',
            sa.Column(
                'is_fee_exempt',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            ),
        )
    if 'premium_expiry' not in existing_columns:
        op.add_column('user', sa.Column('premium_expiry', sa.DateTime(timezone=True), nullable=True))
    if 'last_active_at' not in existing_columns:
        op.add_column('user', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    if 'current_path' not in existing_columns:
        op.add_column('user', sa.Column('current_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_path')
    op.drop_column('user', 'last_active_at')
    op.drop_column('user', 'premium_expiry')
    op.drop_column('user', 'is_fee_exempt')
    op.drop_column('user', 'fee_override')
    # ### end Alembic commands ###
