"""add deduplication fields to Question

Revision ID: 66c79caebbdf
Revises: dfd9b81225f0
Create Date: 2026-02-24 00:14:05.284890

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '66c79caebbdf'
down_revision = 'dfd9b81225f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('standard', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('questions', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('questions', sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_questions_content_hash'), 'questions', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_content_hash'), table_name='questions')
    op.drop_column('questions', 'content_hash')
    op.drop_column('questions', 'category')
    op.drop_column('questions', 'standard')
    # ### end Alembic commands ###
