"""add missing question fields

Revision ID: 6c72d79e43ba
Revises: 3d46a272b5b7
Create Date: 2026-02-13 01:51:25.758395

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6c72d79e43ba'
down_revision = '3d46a272b5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('negative_marks', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('negative_marks')
        batch_op.drop_column('options')
    # ### end Alembic commands ###
