from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '81313a31af60'
down_revision = 'd43372234e99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        # batch_op.add_column(sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('question_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='MCQ'))
        batch_op.add_column(sa.Column('solution_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('option_a',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('option_b',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('option_c',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('option_d',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('correct_option',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'correct_option',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'option_d',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'option_c',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'option_b',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'option_a',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('questions', 'solution_text')
    op.drop_column('questions', 'question_type')
    op.drop_column('questions', 'section')
    op.drop_column('questions', 'subject')
    # ### end Alembic commands ###
