"""add_ai_analysis_to_attempt

Revision ID: 9452d2e1b817
Revises: 33052ad7ba41
Create Date: 2026-02-08 18:54:29.991594

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9452d2e1b817'
down_revision = '33052ad7ba41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('ai_analysis', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempts', 'ai_analysis')
    # ### end Alembic commands ###
