"""add_ai_metadata_and_cache

Revision ID: a8d7ce5d3758
Revises: d268a330e8b6
Create Date: 2026-02-22 00:51:12.300552

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a8d7ce5d3758'
down_revision = 'd268a330e8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_paper_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pdf_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_paper_cache_pdf_hash'), 'parsed_paper_cache', ['pdf_hash'], unique=True)
    op.add_column('questions', sa.Column('organic_metadata', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('diagram_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'diagram_description')
    op.drop_column('questions', 'organic_metadata')
    op.drop_index(op.f('ix_parsed_paper_cache_pdf_hash'), table_name='parsed_paper_cache')
    op.drop_table('parsed_paper_cache')
    # ### end Alembic commands ###
