"""Add solution_bbox

Revision ID: b2c24d78ba8a
Revises: 66c79caebbdf
Create Date: 2026-03-14 11:05:17.015975

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b2c24d78ba8a'
down_revision = '66c79caebbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('solution_bbox', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('questions', 'solution_bbox')
    # ### end Alembic commands ###
