"""add_scheduled_at_to_test

Revision ID: d021cbf3a553
Revises: 9452d2e1b817
Create Date: 2026-02-08 19:36:57.181818

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd021cbf3a553'
down_revision = '9452d2e1b817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('questions', sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tests', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'scheduled_at')
    op.drop_column('questions', 'section')
    op.drop_column('questions', 'subject')
    # ### end Alembic commands ###
