"""Add is_premium to User

Revision ID: d43372234e99
Revises: f9787251840d
Create Date: 2026-02-07 11:02:07.773169

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd43372234e99'
down_revision = 'f9787251840d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_premium', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_premium')
    # ### end Alembic commands ###