"""add pdf_hash to TestGenerationConfig

Revision ID: dfd9b81225f0
Revises: 388905b5f056
Create Date: 2026-02-22 15:52:16.126521

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dfd9b81225f0'
down_revision = '388905b5f056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_generation_configs', sa.Column('pdf_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_test_generation_configs_pdf_hash'), 'test_generation_configs', ['pdf_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_generation_configs_pdf_hash'), table_name='test_generation_configs')
    op.drop_column('test_generation_configs', 'pdf_hash')
    # ### end Alembic commands ###
