"""Add TestGenerationConfig

Revision ID: f548096aeeb5
Revises: d491c587872d
Create Date: 2026-02-15 11:28:40.435851

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f548096aeeb5'
down_revision = 'd491c587872d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_generation_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('config_data', sa.JSON(), nullable=True),
    sa.Column('parsing_report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_generation_configs_test_id'), 'test_generation_configs', ['test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_generation_configs_test_id'), table_name='test_generation_configs')
    op.drop_table('test_generation_configs')
    # ### end Alembic commands ###
