"""Fix options nullability

Revision ID: f5f430f13b96
Revises: 81313a31af60
Create Date: 2026-02-07 12:24:47.485996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f430f13b96'
down_revision = '81313a31af60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('option_a',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('option_b',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('option_c',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('option_d',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('correct_option',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_option',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('option_d',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('option_c',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('option_b',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('option_a',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
    # ### end Alembic commands ###
