"""add_stream_and_standard

Revision ID: fe361ac9d9a8
Revises: d021cbf3a553
Create Date: 2026-02-08 19:42:31.238037

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fe361ac9d9a8'
down_revision = 'd021cbf3a553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('standard', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('user', sa.Column('stream', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stream')
    op.drop_column('user', 'standard')
    # ### end Alembic commands ###
