/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutTeacherDashboardRouteImport } from './routes/_layout/teacher-dashboard'
import { Route as LayoutStudentDashboardRouteImport } from './routes/_layout/student-dashboard'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutGradeSelectionRouteImport } from './routes/_layout/grade-selection'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutTestsTestIdRouteImport } from './routes/_layout/tests.$testId'
import { Route as LayoutAttemptsAttemptIdRouteImport } from './routes/_layout/attempts.$attemptId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTeacherDashboardRoute = LayoutTeacherDashboardRouteImport.update({
  id: '/teacher-dashboard',
  path: '/teacher-dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStudentDashboardRoute = LayoutStudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGradeSelectionRoute = LayoutGradeSelectionRouteImport.update({
  id: '/grade-selection',
  path: '/grade-selection',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTestsTestIdRoute = LayoutTestsTestIdRouteImport.update({
  id: '/tests/$testId',
  path: '/tests/$testId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAttemptsAttemptIdRoute = LayoutAttemptsAttemptIdRouteImport.update({
  id: '/attempts/$attemptId',
  path: '/attempts/$attemptId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/grade-selection': typeof LayoutGradeSelectionRoute
  '/settings': typeof LayoutSettingsRoute
  '/student-dashboard': typeof LayoutStudentDashboardRoute
  '/teacher-dashboard': typeof LayoutTeacherDashboardRoute
  '/attempts/$attemptId': typeof LayoutAttemptsAttemptIdRoute
  '/tests/$testId': typeof LayoutTestsTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/grade-selection': typeof LayoutGradeSelectionRoute
  '/settings': typeof LayoutSettingsRoute
  '/student-dashboard': typeof LayoutStudentDashboardRoute
  '/teacher-dashboard': typeof LayoutTeacherDashboardRoute
  '/attempts/$attemptId': typeof LayoutAttemptsAttemptIdRoute
  '/tests/$testId': typeof LayoutTestsTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/grade-selection': typeof LayoutGradeSelectionRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/student-dashboard': typeof LayoutStudentDashboardRoute
  '/_layout/teacher-dashboard': typeof LayoutTeacherDashboardRoute
  '/_layout/attempts/$attemptId': typeof LayoutAttemptsAttemptIdRoute
  '/_layout/tests/$testId': typeof LayoutTestsTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/grade-selection'
    | '/settings'
    | '/student-dashboard'
    | '/teacher-dashboard'
    | '/attempts/$attemptId'
    | '/tests/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/grade-selection'
    | '/settings'
    | '/student-dashboard'
    | '/teacher-dashboard'
    | '/attempts/$attemptId'
    | '/tests/$testId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/grade-selection'
    | '/_layout/settings'
    | '/_layout/student-dashboard'
    | '/_layout/teacher-dashboard'
    | '/_layout/attempts/$attemptId'
    | '/_layout/tests/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/teacher-dashboard': {
      id: '/_layout/teacher-dashboard'
      path: '/teacher-dashboard'
      fullPath: '/teacher-dashboard'
      preLoaderRoute: typeof LayoutTeacherDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/student-dashboard': {
      id: '/_layout/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof LayoutStudentDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/grade-selection': {
      id: '/_layout/grade-selection'
      path: '/grade-selection'
      fullPath: '/grade-selection'
      preLoaderRoute: typeof LayoutGradeSelectionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tests/$testId': {
      id: '/_layout/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof LayoutTestsTestIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/attempts/$attemptId': {
      id: '/_layout/attempts/$attemptId'
      path: '/attempts/$attemptId'
      fullPath: '/attempts/$attemptId'
      preLoaderRoute: typeof LayoutAttemptsAttemptIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutGradeSelectionRoute: typeof LayoutGradeSelectionRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStudentDashboardRoute: typeof LayoutStudentDashboardRoute
  LayoutTeacherDashboardRoute: typeof LayoutTeacherDashboardRoute
  LayoutAttemptsAttemptIdRoute: typeof LayoutAttemptsAttemptIdRoute
  LayoutTestsTestIdRoute: typeof LayoutTestsTestIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutGradeSelectionRoute: LayoutGradeSelectionRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStudentDashboardRoute: LayoutStudentDashboardRoute,
  LayoutTeacherDashboardRoute: LayoutTeacherDashboardRoute,
  LayoutAttemptsAttemptIdRoute: LayoutAttemptsAttemptIdRoute,
  LayoutTestsTestIdRoute: LayoutTestsTestIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
